### ISSUE TITLE
Error during execution

### ISSUE THREAD

**Issue by sohrabtowfighi** [dn1z/pgn2gif#6]
Traceback (most recent call last):
  File "pgn2gif.py", line 311, in <module>
    process_file(args.path, args.speed, args.out, args.reverse)
  File "pgn2gif.py", line 295, in process_file
    create_gif(pgn, name, duration, output_dir, reverse)
  File "pgn2gif.py", line 272, in create_gif
    update(move, i % 2)
  File "pgn2gif.py", line 58, in update
    to = point_of_square(move)
  File "pgn2gif.py", line 41, in point_of_square
    r = 7 - rows.index(move[-1])
ValueError: '0' is not in list

If anyone stumbles on this issue, I noticed that get_moves_from_pgn regex may fail if pgn tags have usernames or other info matching regex

I noticed that my pgn file has this line
[White "bac02"], which when deleted makes the code run fine.
Thanks!

**Comment by dn1z** [comment]
Thanks for reporting. I'll update regex.
